service: anniversary
useDotenv: true
frameworkVersion: '2'
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    GITHUB_PERSONAL_ACCESS_TOKEN: ${env:GITHUB_PERSONAL_ACCESS_TOKEN}
    WORKFLOW_DISPATCH_PATH: ${env:WORKFLOW_DISPATCH_PATH}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline